### PR TITLE
fix(node): drop undefined exhaustive/MatchException in matchImpl fallback

### PR DESCRIPTION
**Pull request by CyberShadow**
`matchImpl` (in `source/uninode/node.d`) ends a `static foreach` chain of `MatchType` arm checks with a fallback `else`-branch that references two identifiers that do not exist in this project:

```d
    else
    {
        static if(exhaustive)
            static assert(false,
                "No matching handler for type `" ~ T.stringof ~ "`");
        else
            throw new MatchException(
                "No matching handler for type `" ~ T.stringof ~ "`");
    }
```

Neither `exhaustive` nor `MatchException` is declared anywhere in the project. The shape of the branch (an `exhaustive` toggle picking between a static-assert and a thrown match exception) mirrors the `visit`/`tryVisit` split in `std.variant`, so it appears to be vestige from an earlier iteration where this template took a flag and supported both modes. Whatever the origin, the references have been broken since this code was introduced.

In normal use this branch is unreachable: the preceding arms cover every real `MatchType` produced by `HandlerMatch`, so codegen never reaches the `else`. As a result the unresolved identifiers were latent and silently shipped.

Starting with DMD 2.112 this becomes user-visible. A separate upstream DMD regression in `core.internal.newaa` (templated AA equality on a recursive `struct` reachable via `alias this`) silently flips `canMatch!(handler, UniNode[string])` from `true` to `false` inside `is(typeof(...))`. With no candidate handler matching, `HandlerMatch` returns `MatchType.NO`, the chain falls through, and DMD then has to elaborate the dead `else` and reports:

    source/uninode/node.d(1131): Error: undefined identifier `exhaustive`
    source/uninode/node.d(1135): Error: undefined identifier `MatchException`

These two errors then cascade into a sequence of misleading constructor-overload and template-constraint errors elsewhere in `node.d` (in `_val`, `toHash`, etc.) as DMD's recovery synthesises broken instantiations.

Fix: collapse the broken branch to the single static-assert path. There is no `exhaustive` template parameter in scope to toggle on, and no `MatchException` type to throw. A "no matching handler" condition is genuinely a programmer error here, so a compile-time assert is the right behaviour.

This does not fix the underlying DMD 2.112 regression — the build still fails on 2.112 — but it reduces the failure from a multi-error cascade of red-herring messages to a single, accurate diagnostic:

    source/uninode/node.d(NNNN): Error: static assert: \
        "No matching handler for type `UniNode[string]`"

which points at the actual symptom (a sumtype variant has no matching handler) rather than at unrelated symbols. Builds on 2.110 and 2.111 (which the project does currently support) are unaffected — the branch is still dead there, just no longer broken.

I'll pursue the DMD-side regressions separately.

### CODE REVIEW

**Comment by CyberShadow** [comment]
> I'll pursue the DMD-side regressions separately.

Here they are:

- https://github.com/dlang/dmd/issues/23064
- https://github.com/dlang/dmd/issues/23065
